apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-playground
  namespace: nowapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: now-playground
  template:
    metadata:
      labels:
        app: now-playground
    spec:
      containers:
        - name: now-playground
          image: jinaai/now-playground:{docker_bff_playground_tag}
          imagePullPolicy: Always
          command: ["streamlit"]
          args: ["run", "playground.py", "--server.port", "80"]
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-bff
  namespace: nowapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: now-bff
  template:
    metadata:
      labels:
        app: now-bff
    spec:
      containers:
        - name: now-bff
          image: jinaai/now-bff:{docker_bff_playground_tag}
          imagePullPolicy: Always
          command: ['uvicorn']
          args:  ["deployment.bff.app.app:application", "--host", "0.0.0.0", "--port", "80", "--loop", "uvloop"]
          ports:
            - containerPort: 80
