name: push executor
description: push executor to the hub
inputs:
  executor_version_name:
    description: The name of the executor to update.
  executor_name:
    description: The name of the executor to update.
  executor_path:
    description: The path of the executor to update.
  has_changed_filter:
    description: The filter to use for checking if the component has changed.
  executor_id:
    description: The id of the executor to update.
  jina_auth_token:
      description: The filter to use for checking if the component has changed.


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Check if code relevant to executor has changed
      uses: dorny/paths-filter@v2
      id: check_has_executor_changed
      with:
        filters: |
          has_executor_changed:
            - now/app/base/**
            - now/executor/abstract/auth/**
            - requirements.txt
            ${{ inputs.has_changed_filter }}
    - name: Get executor tag
      if: steps.check_has_executor_changed.outputs.has_executor_changed == 'true'
      shell: bash
      run: |
        FILE='now/constants.py'
        VERSION=$(sed -n '/${{ inputs.executor_version_name }} =/p' $FILE | cut -d \' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Set up Python 3.7
      if: steps.check_has_executor_changed.outputs.has_executor_changed == 'true'
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Pip install jina
      if: steps.check_has_executor_changed.outputs.has_executor_changed == 'true'
      shell: bash
      run: pip install "jina[perf]==3.14.2.dev18"
    - name: Check that tag isn't used already for executor
      if: steps.check_has_executor_changed.outputs.has_executor_changed == 'true'
      env:
        VERSION: ${{ env.VERSION }}
      shell: bash
      run: |
        if jina hub pull jinahub+docker://${{ inputs.executor_id }}/$VERSION; then
          echo "Executor version/tag is used already. Please update the tag"
          exit 1
        else
          echo "Executor version/tag isn't used already, continue to build..."
        fi
    # append the now requirements to the executor requirements for performance improvements
    # that way the requirements are cached and don't need to be reinstalled every time someone changes the source code
    - name: optimization of executor build time
      if: steps.check_has_executor_changed.outputs.has_executor_changed == 'true'
      shell: bash
      run: |
        dest=${{ inputs.executor_path }}/requirements.txt
        # one extra line to not break the requirements.txt file
        echo '' >> $dest
        cat requirements.txt >> $dest
    # set correct now version in the dockerfile
    - name: replace now commit hash in Dockerfile
      if: steps.check_has_executor_changed.outputs.has_executor_changed == 'true'
      shell: bash
      run: sed -i 's/JINA_NOW_COMMIT_SHA/${{ github.event.pull_request.head.sha }}/g' ${{ inputs.executor_path }}/Dockerfile
    - name: Build and push executor
      if: steps.check_has_executor_changed.outputs.has_executor_changed == 'true'
      shell: bash
      env:
        VERSION: ${{ env.VERSION }}
      run: JINA_AUTH_TOKEN=${{ inputs.jina_auth_token }} jina hub push --verbose --force-update ${{ inputs.executor_name }} ${{ inputs.executor_path }}/. -t latest --protected-tag $VERSION
