name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_reason:
        description: 'Short reason for this manual release'
        required: true

jobs:
  regular-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          fetch-depth: 100  # means max contribute history is limited to 100 lines
#          submodules: true
      # TODO Remove after issue is fixed
      # see https://github.com/actions/runner-images/issues/7048#issuecomment-1419426054
      - name: Set apt mirror
        run: |
          # make sure there is a `\t` between URL and `priority:*` attributes
          printf 'http://azure.archive.ubuntu.com/ubuntu	priority:1\n' | sudo tee /etc/apt/mirrors.txt
          curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
          sudo sed -i 's/http:\/\/azure.archive.ubuntu.com\/ubuntu\//mirror+file:\/etc\/apt\/mirrors.txt/' /etc/apt/sources.list
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          npm install git-release-notes
          pip install twine wheel
          ./scripts/release.sh final "${{ github.event.inputs.release_reason }}" "${{github.actor}}"
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          JINA_SLACK_WEBHOOK: ${{ secrets.JINA_SLACK_WEBHOOK }}
      - if: failure()
        run: echo "nothing to release"
      - name: bumping master version
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          tags: true
          branch: main


  trigger-now-private:
    name: Trigger dispatch to release now_api with latest Jina NOW
    runs-on: ubuntu-latest
    needs: [regular-release]
    steps:
      - name: Dispatch to now.private to package now_api
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.NOW_PREPROCESSOR_REPO_TOKEN }}
          repository: ${{ secrets.NOW_PREPROCESSOR_REPO }}
          event-type: update_api