name: Manual Docs Build

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'CD | TAG | MANUAL'
        required: false
        default: MANUAL

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # TODO Remove after issue is fixed
      # see https://github.com/actions/runner-images/issues/7048#issuecomment-1419426054
      - name: Set apt mirror
        run: |
          # make sure there is a `\t` between URL and `priority:*` attributes
          printf 'http://azure.archive.ubuntu.com/ubuntu	priority:1\n' | sudo tee /etc/apt/mirrors.txt
          curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
          sudo sed -i 's/http:\/\/azure.archive.ubuntu.com\/ubuntu\//mirror+file:\/etc\/apt\/mirrors.txt/' /etc/apt/sources.list
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build doc and push to gh-pages
        run: |
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
          pip install .
          mkdir gen-html
          cd docs
          pip install -r requirements.txt
          pip install --pre -U furo
          bash makedoc.sh
          cd ./_build/dirhtml/
          cp -r ./ ../../../gen-html
          cd -  # back to ./docs
          cd ..
          git checkout -f gh-pages
          git rm -rf ./docs
          mkdir -p docs
          cd gen-html
          cp -r ./ ../docs
          cd ../docs
          ls -la
          touch .nojekyll
          cp 404/index.html 404.html
          sed -i 's/href="\.\./href="/' 404.html # fix asset urls that needs to be updated in 404.html
          echo now.jina.ai > CNAME
          cd ..
          git add docs
          git status
          git commit -m "chore(docs): update docs due to ${{github.event_name}} on ${{github.repository}}"
          git push --force origin gh-pages